### PR TITLE
Rename mongod service to mongodb

### PR DESCRIPTION
**Pull request by jedahan**
I had to do this to work with latest mongo on my raspberry pi 2

### CODE REVIEW

**Comment by selamanse** [comment]
@jedahan I think the service has to be addressed differently per os then...because on debian it's officially **mongod** and on arm (I guess because of the older version of mongo) it is **mongodb**. Can you please change the lines regarding the mongodb service handling to be in the if-block?

**Comment by jedahan** [comment]
Doesn't even matter - raspbian only supports mongodb 2.4 which is not supported by rocketchat

**Comment by jedahan** [comment]
I'm making a bunch of changes to see if I can install a modern mongodb on rpi2

**Review by selamanse — APPROVED** [review]
Looks good to me - the waitforservice is now a bit more readable. ci will show if the switch between armhf and debian mongo handling will work. Something with the basic linter test fails now. can you look into it @jedahan ?

**Comment by jedahan** [comment]
Yeah I am going to close this PR until I get it working locally, then re-open when its ready. ETA 2 days.

**Pull request closed without merging**
